const types = [
  {"description":"Chan 1 Note off","code":128},
  {"description":"Chan 2 Note off","code":129},
  {"description":"Chan 3 Note off","code":130},
  {"description":"Chan 4 Note off","code":131},
  {"description":"Chan 5 Note off","code":132},
  {"description":"Chan 6 Note off","code":133},
  {"description":"Chan 7 Note off","code":134},
  {"description":"Chan 8 Note off","code":135},
  {"description":"Chan 9 Note off","code":136},
  {"description":"Chan 10 Note off","code":137},
  {"description":"Chan 11 Note off","code":138},
  {"description":"Chan 12 Note off","code":139},
  {"description":"Chan 13 Note off","code":140},
  {"description":"Chan 14 Note off","code":141},
  {"description":"Chan 15 Note off","code":142},
  {"description":"Chan 16 Note off","code":143},
  {"description":"Chan 1 Note on","code":144},
  {"description":"Chan 2 Note on","code":145},
  {"description":"Chan 3 Note on","code":146},
  {"description":"Chan 4 Note on","code":147},
  {"description":"Chan 5 Note on","code":148},
  {"description":"Chan 6 Note on","code":149},
  {"description":"Chan 7 Note on","code":150},
  {"description":"Chan 8 Note on","code":151},
  {"description":"Chan 9 Note on","code":152},
  {"description":"Chan 10 Note on","code":153},
  {"description":"Chan 11 Note on","code":154},
  {"description":"Chan 12 Note on","code":155},
  {"description":"Chan 13 Note on","code":156},
  {"description":"Chan 14 Note on","code":157},
  {"description":"Chan 15 Note on","code":158},
  {"description":"Chan 16 Note on","code":159},
  {"description":"Chan 1 Polyphonic Aftertouch","code":160},
  {"description":"Chan 2 Polyphonic Aftertouch","code":161},
  {"description":"Chan 3 Polyphonic Aftertouch","code":162},
  {"description":"Chan 4 Polyphonic Aftertouch","code":163},
  {"description":"Chan 5 Polyphonic Aftertouch","code":164},
  {"description":"Chan 6 Polyphonic Aftertouch","code":165},
  {"description":"Chan 7 Polyphonic Aftertouch","code":166},
  {"description":"Chan 8 Polyphonic Aftertouch","code":167},
  {"description":"Chan 9 Polyphonic Aftertouch","code":168},
  {"description":"Chan 10 Polyphonic Aftertouch","code":169},
  {"description":"Chan 11 Polyphonic Aftertouch","code":170},
  {"description":"Chan 12 Polyphonic Aftertouch","code":171},
  {"description":"Chan 13 Polyphonic Aftertouch","code":172},
  {"description":"Chan 14 Polyphonic Aftertouch","code":173},
  {"description":"Chan 15 Polyphonic Aftertouch","code":174},
  {"description":"Chan 16 Polyphonic Aftertouch","code":175},
  {"description":"Chan 1 Control/Mode Change","code":176},
  {"description":"Chan 2 Control/Mode Change","code":177},
  {"description":"Chan 3 Control/Mode Change","code":178},
  {"description":"Chan 4 Control/Mode Change","code":179},
  {"description":"Chan 5 Control/Mode Change","code":180},
  {"description":"Chan 6 Control/Mode Change","code":181},
  {"description":"Chan 7 Control/Mode Change","code":182},
  {"description":"Chan 8 Control/Mode Change","code":183},
  {"description":"Chan 9 Control/Mode Change","code":184},
  {"description":"Chan 10 Control/Mode Change","code":185},
  {"description":"Chan 11 Control/Mode Change","code":186},
  {"description":"Chan 12 Control/Mode Change","code":187},
  {"description":"Chan 13 Control/Mode Change","code":188},
  {"description":"Chan 14 Control/Mode Change","code":189},
  {"description":"Chan 15 Control/Mode Change","code":190},
  {"description":"Chan 16 Control/Mode Change","code":191},
  {"description":"Chan 1 Program Change","code":192},
  {"description":"Chan 2 Program Change","code":193},
  {"description":"Chan 3 Program Change","code":194},
  {"description":"Chan 4 Program Change","code":195},
  {"description":"Chan 5 Program Change","code":196},
  {"description":"Chan 6 Program Change","code":197},
  {"description":"Chan 7 Program Change","code":198},
  {"description":"Chan 8 Program Change","code":199},
  {"description":"Chan 9 Program Change","code":200},
  {"description":"Chan 10 Program Change","code":201},
  {"description":"Chan 11 Program Change","code":202},
  {"description":"Chan 12 Program Change","code":203},
  {"description":"Chan 13 Program Change","code":204},
  {"description":"Chan 14 Program Change","code":205},
  {"description":"Chan 15 Program Change","code":206},
  {"description":"Chan 16 Program Change","code":207},
  {"description":"Chan 1 Channel Aftertouch","code":208},
  {"description":"Chan 2 Channel Aftertouch","code":209},
  {"description":"Chan 3 Channel Aftertouch","code":210},
  {"description":"Chan 4 Channel Aftertouch","code":211},
  {"description":"Chan 5 Channel Aftertouch","code":212},
  {"description":"Chan 6 Channel Aftertouch","code":213},
  {"description":"Chan 7 Channel Aftertouch","code":214},
  {"description":"Chan 8 Channel Aftertouch","code":215},
  {"description":"Chan 9 Channel Aftertouch","code":216},
  {"description":"Chan 10 Channel Aftertouch","code":217},
  {"description":"Chan 11 Channel Aftertouch","code":218},
  {"description":"Chan 12 Channel Aftertouch","code":219},
  {"description":"Chan 13 Channel Aftertouch","code":220},
  {"description":"Chan 14 Channel Aftertouch","code":221},
  {"description":"Chan 15 Channel Aftertouch","code":222},
  {"description":"Chan 16 Channel Aftertouch","code":223},
  {"description":"Chan 1 Pitch Bend Change","code":224},
  {"description":"Chan 2 Pitch Bend Change","code":225},
  {"description":"Chan 3 Pitch Bend Change","code":226},
  {"description":"Chan 4 Pitch Bend Change","code":227},
  {"description":"Chan 5 Pitch Bend Change","code":228},
  {"description":"Chan 6 Pitch Bend Change","code":229},
  {"description":"Chan 7 Pitch Bend Change","code":230},
  {"description":"Chan 8 Pitch Bend Change","code":231},
  {"description":"Chan 9 Pitch Bend Change","code":232},
  {"description":"Chan 10 Pitch Bend Change","code":233},
  {"description":"Chan 11 Pitch Bend Change","code":234},
  {"description":"Chan 12 Pitch Bend Change","code":235},
  {"description":"Chan 13 Pitch Bend Change","code":236},
  {"description":"Chan 14 Pitch Bend Change","code":237},
  {"description":"Chan 15 Pitch Bend Change","code":238},
  {"description":"Chan 16 Pitch Bend Change","code":239},
  {"description":"System Exclusive","code":240},
  {"description":"MIDI Time Code Qtr. Frame","code":241},
  {"description":"Song Position Pointer","code":242},
  {"description":"Song Select (Song #)","code":243},
  {"description":"Undefined (Reserved)","code":244},
  {"description":"Undefined (Reserved)","code":245},
  {"description":"Tune request","code":246},
  {"description":"End of SysEx (EOX)","code":247},
  {"description":"Timing clock","code":248},
  {"description":"Undefined (Reserved)","code":249},
  {"description":"Start","code":250},
  {"description":"Continue","code":251},
  {"description":"Stop","code":252},
  {"description":"Undefined (Reserved)","code":253},
  {"description":"Active Sensing","code":254},
  {"description":"System Reset","code":255}
];
export default {
  getTypeByCode(code) {
    return types.find(type => type.code === code);
  }
};
